### ISSUE TITLE
https protocol not supported, please fix invalid link

### ISSUE THREAD

**Issue by joulupukki77** [aajanki/yle-dl#99] opened 2017-05-09 11:04 UTC
In the class ArkivetDownloader, in the function program_info_url, on line 1438, https should be replaced with http in the link:

Current line 1438, not working:
return 'https://player.yle.fi/api/v1/arkivet.jsonp?' \

Should look like this:
return 'http://player.yle.fi/api/v1/arkivet.jsonp?' \

Just change https to http in the link.

Thank you for your effort.

**Comment by aajanki** [comment] 2017-05-10 18:22
It currently works for me even with https. For example, `yle-dl https://svenska.yle.fi/artikel/2009/05/05/guldfest-i-helsingfors-1995`

Can you give an example Arkivet page where changing the link improves things?

Many videos do fail with "Unsupported stream: Failed to parse media ID" or similar error, but they fail even if I change the link to http.

**Comment by aajanki** [comment] 2017-05-27 07:21
I'm closing this bug report, because I can't reproduce it.

**Closed by aajanki** 2017-05-27 07:21 UTC
