### ISSUE TITLE
Unable to remux into mp4 a video with a colon in the title

### ISSUE THREAD

**Issue by jpsalo** [aajanki/yle-dl#96] opened 2017-03-18 16:45 UTC
`--postprocess scripts/muxmp4` fails with a message from `ffmpeg`

> No such file or directory

when the title has a colon, for example an episode of [Perjantai](http://areena.yle.fi/1-3768892).

I tried with `--vfat` which gets rid of the colon, but I guess that a space in the file name does not work then.

**Comment by aajanki** [comment] 2017-03-20 18:27
Works for me.

The error you get might mean that the post processing script itself is not found. Try using the absolute path `--postprocess /path/to/scripts/muxmp4`.

**Comment by aajanki** [comment] 2017-05-10 18:23
Closing because I can't reproduce.

**Closed by aajanki** 2017-05-10 18:23 UTC

**Comment by gunnar12** [comment] 2017-06-15 15:51
gets rid of the colon, but I guess that a space/

Yep, windos cant take colons.

Ffmpeg like most everyone, esp windoze needs quotation marks around filenames with spaces.

PS the real little prblm is that "minus sign" which actly is a "dash" and UT-encoded.
