### ISSUE TITLE
newnew 1-500 Sports download gives lowest  resolution

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#188] opened 2019-03-09 22:45 UTC

**Comment by gunnar12** [comment] 2019-03-09 22:56
yle-dl - ffmpeg seems to always pick lowest resolution after listing up to the highest resolution.

Either "from the very start" or probably after that " areena logo" on black background.
(it seems to be a separate stream??)

"old style" streams are highest resolution althgh it might tal until "tomorrow" before YLE  gets them done (aamuTV)

https://areena.yle.fi/1-50083652

  Program 10 
    Metadata:
      variant_bitrate : 6500000
    Stream #0:30: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 6500000
    Stream #0:31: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 6500000
    Stream #0:32: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 6500000
  Program 11 
    Metadata:
      variant_bitrate : 6500000
    Stream #0:33: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 6500000
    Stream #0:34: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 6500000
    Stream #0:35: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 6500000
Output #0, mp4, to 'file:Alppihiihdon maailmancup_ Alppihiihdon MC_ Kranjska Gora, miesten suurpujottelu, 1. lasku-2019-03-09T10_28+02_00.mp4':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 480x270 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 530000

xxxxx

picks  480x270 !

**Comment by aajanki** [comment] 2019-03-10 19:08
Duplicate of #181

**Comment by WildPenquin** [comment] 2019-04-24 07:30
Hi,

Is there any way to select anything than a higher-than-lowest bitrate currently?

In case I've mistaken and this is the incorrect / different issue, this is the stream I'm having trouble with: https://areena.yle.fi/1-50118986

**Comment by aajanki** [comment] 2019-04-25 18:46
That stream seems to be affect by this issue. It's not possible to select another bitrate at the moment, sorry.

**Closed** 2019-04-27 16:51 UTC
