### ISSUE TITLE
Yle-dl needs to get new Akamai Cookie when wget re-tries

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#175] opened 2018-11-25 17:40 UTC
Yle-dl needs to get new Akamai Cookie when wget re-tries, at least when expiration cookie-part (exp=) an hour or so old.
Akamai servers seem to always return "403 forbidden" when cookie has expired.

This, obv, only happens when the doenload file is multyGbyte and/or one downloads some other things at the same time so that downloading takes a "very" long time.
If properly set, the start-exp cookie is set according to, proportionally to duration of stream by Akamai?

Resolving ylekaod-a.akamaihd.net... 217.212.252.105, 217.212.252.88
Connecting to ylekaod-a.akamaihd.net|217.212.252.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6242231348 (5,8G) [video/mp4]
Saving to: ‘Världscupen i backhoppning (svenskt referat)-2018-11-24T20_07_52+02_00.mp4’

Världscupen i backhoppning  71%[============================>            ]   4,16G   284KB/s    in 4h 0m   

2018-11-25 19:24:32 (303 KB/s) - Connection closed at byte 4471128064. Retrying.

--2018-11-25 19:24:33--  (try: 2)  https://ylekaod-a.akamaihd.net/s/p/1955031/sp/0/serveFlavor/entryId/1_g1bbcv48/v/11/flavorId/1_4j2udv6c/name/a.mp4?__hdnea__=st=1543152256~exp=1543166656~acl=/s/p/1955031/sp/0/serveFlavor/entryId/1_g1bbcv48/v/11/flavorId/1_4j2udv6c/name/a.mp4*~hmac=78fe1f5b26b67dc64566a5d687bc9096c7fab749b752bef40ea157e1f8b0d663
Connecting to ylekaod-a.akamaihd.net|217.212.252.105|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-11-25 19:24:33 ERROR 403: Forbidden.

After this yle-dl clears the dwnld file and continues with ffmpg, but obv from zero..

PS I remember seeing some code to construct, calculate, set ones own new valid cookie.
I think it was for the "trivial" case, just start, (new) expiration and something hacked to get the hmac value?
ANyone who knows.

PPS But with wget resume yle-dl cld just get a new cookie, restart wget.
hmmm.. I wonder if ffmpg does the simple recalculation (not cracking a possible secret token,etc)

**Comment by aajanki** [comment] 2018-11-26 18:37
Yes, yle-dl should get a new stream URL from scratch when retrying.

**Comment by aajanki** [comment] 2018-11-26 18:37
Duplicate of #157

**Closed** 2022-07-18 12:04 UTC
