### ISSUE TITLE
Installation failure, ImportError: No module named yledl.yledl

### ISSUE THREAD

**Issue by jk-1** [aajanki/yle-dl#141] opened 2017-12-31 09:30 UTC
I installed yle-dl according this guide: https://github.com/aajanki/yle-dl/blob/master/OS-install-instructions.md
OS is Ubuntu 16.04

WHen I try any yle-dl command, output is as follows:

	yle-dl --help
	Traceback (most recent call last):
	  File "/usr/local/bin/yle-dl", line 7, in <module>
		from yledl.yledl import main
	ImportError: No module named yledl.yledl

How to fix this?

Installing yle-dl went OK:

	sudo apt-get install rtmpdump wget ffmpeg python-dev python-setuptools python-pip python-crypto python-requests python-lxml php-cli php-curl php-mcrypt php-xml php-bcmath

	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	python-lxml is already the newest version (3.5.0-1build1).
	python-lxml set to manually installed.
	python-requests is already the newest version (2.9.1-3).
	python-crypto is already the newest version (2.6.1-6ubuntu0.16.04.2).
	wget is already the newest version (1.17.1-1ubuntu1.3).
	The following additional packages will be installed:
	  libavdevice-ffmpeg56 libexpat1-dev libmcrypt4 libpython-all-dev libpython-dev libpython2.7-dev libvdpau1 mesa-vdpau-drivers php-common php7.0-bcmath php7.0-cli php7.0-common php7.0-curl php7.0-json php7.0-mcrypt php7.0-opcache php7.0-readline php7.0-xml python-all python-all-dev python-pip-whl python-wheel python2.7-dev vdpau-driver-all
	Suggested packages:
	  ffmpeg-doc libmcrypt-dev mcrypt php-pear python-setuptools-doc libvdpau-va-gl1 nvidia-vdpau-driver nvidia-legacy-340xx-vdpau-driver
	The following NEW packages will be installed:
	  ffmpeg libavdevice-ffmpeg56 libexpat1-dev libmcrypt4 libpython-all-dev libpython-dev libpython2.7-dev libvdpau1 mesa-vdpau-drivers php-bcmath php-cli php-common php-curl php-mcrypt php-xml php7.0-bcmath php7.0-cli php7.0-common php7.0-curl php7.0-json php7.0-mcrypt php7.0-opcache php7.0-readline php7.0-xml python-all python-all-dev python-dev
	  python-pip python-pip-whl python-setuptools python-wheel python2.7-dev rtmpdump vdpau-driver-all
	0 upgraded, 34 newly installed, 0 to remove and 3 not upgraded.
	Need to get 35,3 MB of archives.
	After this operation, 77,9 MB of additional disk space will be used.
	Do you want to continue? [Y/n] 

	sudo phpenmod mcrypt

	sudo -H pip install --upgrade yle-dl

	Collecting yle-dl
	  Downloading yle_dl-2.30-py2.py3-none-any.whl (45kB)
		100% |████████████████████████████████| 51kB 600kB/s 
	Collecting Py3AMF (from yle-dl)
	  Downloading Py3AMF-0.8.7.tar.gz (1.6MB)
		100% |████████████████████████████████| 1.6MB 524kB/s 
	Collecting requests (from yle-dl)
	  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
		100% |████████████████████████████████| 92kB 2.4MB/s 
	Collecting future (from yle-dl)
	  Downloading future-0.16.0.tar.gz (824kB)
		100% |████████████████████████████████| 829kB 864kB/s 
	Requirement already up-to-date: pycrypto in /usr/lib/python2.7/dist-packages (from yle-dl)
	Collecting lxml (from yle-dl)
	  Downloading lxml-4.1.1-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
		100% |████████████████████████████████| 5.6MB 271kB/s 
	Collecting defusedxml (from Py3AMF->yle-dl)
	  Downloading defusedxml-0.5.0-py2.py3-none-any.whl
	Collecting urllib3<1.23,>=1.21.1 (from requests->yle-dl)
	  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
		100% |████████████████████████████████| 133kB 3.4MB/s 
	Collecting idna<2.7,>=2.5 (from requests->yle-dl)
	  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
		100% |████████████████████████████████| 61kB 2.8MB/s 
	Collecting chardet<3.1.0,>=3.0.2 (from requests->yle-dl)
	  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
		100% |████████████████████████████████| 143kB 3.5MB/s 
	Collecting certifi>=2017.4.17 (from requests->yle-dl)
	  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
		100% |████████████████████████████████| 337kB 1.9MB/s 
	Building wheels for collected packages: Py3AMF, future
	  Running setup.py bdist_wheel for Py3AMF ... done
	  Stored in directory: /root/.cache/pip/wheels/25/0b/76/6981f861a2aef3724fc8e442f3c6bf0542786f10fc7fe5b7a1
	  Running setup.py bdist_wheel for future ... done
	  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
	Successfully built Py3AMF future
	Installing collected packages: defusedxml, Py3AMF, urllib3, idna, chardet, certifi, requests, future, lxml, yle-dl
	  Found existing installation: urllib3 1.13.1
		Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, outside environment /usr
	  Found existing installation: chardet 2.3.0
		Not uninstalling chardet at /usr/lib/python2.7/dist-packages, outside environment /usr
	  Found existing installation: requests 2.9.1
		Not uninstalling requests at /usr/lib/python2.7/dist-packages, outside environment /usr
	  Found existing installation: lxml 3.5.0
		Not uninstalling lxml at /usr/lib/python2.7/dist-packages, outside environment /usr
	Successfully installed Py3AMF-0.8.7 certifi-2017.11.5 chardet-3.0.4 defusedxml-0.5.0 future-0.16.0 idna-2.6 lxml-4.1.1 requests-2.18.4 urllib3-1.22 yle-dl-2.30
	You are using pip version 8.1.1, however version 9.0.1 is available.
	You should consider upgrading via the 'pip install --upgrade pip' command.

Thank you for your support and help!

**Comment by aajanki** [comment] 2018-01-02 11:03
Can you attach the outputs of the following commands also in this case?
* `export | grep PYTHONPATH`
* `/usr/bin/python -c 'import sys; print(sys.path)'`

**Comment by jk-1** [comment] 2018-01-03 05:51
jk@mypc:~$ export | grep PYTHONPATH

	jk@mypc:~$ /usr/bin/python -c 'import sys; print(sys.path)'
	['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', 
	'/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0']

	jk@mypc:~$ which yle-dl
	/usr/local/bin/yle-dl

**Comment by aajanki** [comment] 2018-06-19 16:16
I'm closing this issue because I can reproduce it. Probably the same issues as #142

**Closed by aajanki** 2018-06-19 16:16 UTC

**Comment by matiasw** [comment] 2023-10-27 21:29
@aajanki I am facing this issue when installing on WSL2 Kali Linux. 

`pipx install yle-dl` gave 
```
⚠️  File exists at /home/appas/.local/bin/yle-dl and points to /home/appas/.local/bin/yle-dl, not
    /home/appas/.local/pipx/venvs/yle-dl/bin/yle-dl. Not modifying.
  installed package yle-dl 20230611, installed using Python 3.11.6
    - yle-dl (symlink missing or pointing to unexpected location)
done! ✨ 🌟 ✨
```
...and then `yle-dl` gives 
```Traceback (most recent call last):
  File "/home/appas/.local/bin/yle-dl", line 5, in <module>
    from yledl.yledl import main
ModuleNotFoundError: No module named 'yledl'
```

**Comment by Mikaela** [comment] 2023-10-28 06:48
You seem to have two copies of yle-dl. I would try `pip uninstall yle-dl --user` (or does pip use the verb `remove`?) before trying `pipx install yle-dl` (or possibly `pipx reinstall yle-dl`).

**Comment by matiasw** [comment] 2023-10-28 06:54
>  `pipx reinstall yle-dl`

Yeah this did it. I did previously try to re-install, but I guess I fudged it up somehow.
