### ISSUE TITLE
Feature-request: "--skip" to skip existing episodes in destination dir

### ISSUE THREAD

**Issue by nation-wide** [aajanki/yle-dl#212] opened 2019-08-19 07:54 UTC
Right now if you try to download same episode again, yle-dl reports:

`FILENAME.EXT exists, trying an alternative name`

And the episode is saved as FILENAME-1.EXT.

Please add an option (f.ex --skip) to skip existing episodes in destination dir.

This way user does not have to manually clean-up duplicates when the use of yle-dl is automated.

**Comment by aajanki** [comment] 2019-08-20 17:54
The `--resume` switch is supposed to skip already downloaded episodes like you suggest, but it is buggy at the moment (issue #183).

**Comment by aajanki** [comment] 2019-08-20 17:54
Duplicate of #183

**Closed** 2019-10-19 16:41 UTC

**Comment by aajanki** [comment] 2019-10-19 16:43
When the `--resume` switch is enabled, yle-dl will now check if the file has already been completely downloaded and skip re-downloading it if that is the case.
