### ISSUE TITLE
Subtitles only partially downloaded

### ISSUE THREAD

**Issue by mkarppa** [aajanki/yle-dl#180] opened 2019-02-06 05:23 UTC
It seems that, on the new version (20190203), when you use the ffmpeg backend (ffmpeg version 3.4.4-0ubuntu0.18.04.1), subtitles are downloaded only partially. The resulting mp4 only contains timecodes for subtitles up to about 5 minutes into the video, then nothing. This seems to affect at least the following:
https://areena.yle.fi/1-4457872
https://areena.yle.fi/1-3927424
and probably more.

No errors appear in the ffmpeg output on the command line. Is this something new, or are there workarounds, anything?

edit: It seems that there is some consistency in that the subtitles are dropped after 5 minutes. No idea what's wrong, though.

**Comment by aajanki** [comment] 2019-02-06 19:47
This could be due to too old ffmpeg. I have ffmpeg version 4.1-1 and I can see the subtitles for the full length of the video in both cases.

Are you able to test with the latest ffmpeg?

**Comment by mkarppa** [comment] 2019-02-10 19:26
I compiled a custom build of ffmpeg 4.1, and this seems to have solved the issue, thanks.

However, I think it would be prudent to mention the fact that a sufficiently recent ffmpeg is required on the website since the version supplied with Ubuntu 18.04 LTS (including the relevant derivatives, such as Linux Mint) is too old.

**Comment by aajanki** [comment] 2019-02-11 17:59
I added the ffmpeg version requirement on the web page a couple of days ago.

So, at the moment, the only supported way to download subtitles is to use ffmpeg 4.1. I hope to find a workaround for older ffmpegs, but let's see if that is possible.

**Comment by lsolin** [comment] 2019-02-12 00:08
I went back to version 20181221 because wget works faster on my system (16.04) and I want to select external subtitles and I don't have the latest ffmpeg. Also when downloading with ffmpeg, Vlc won't play the stream until the download is ready.

Was it because of subtitle downloading problems that ffmpeg was preferred? I haven't had any of those problems for a long time.

Thanks for a great program!

**Comment by Jormangeud** [comment] 2019-02-12 02:36
Also, the readme should probably mention that ffmpeg needs to be compiled with ssl support as well.

**Comment by roostaq** [comment] 2019-04-22 10:10
I can confirm that for some things, it doesn't download them at all. (ex: Invisible Heroes)
I am using the latest ffmepg from `git://git.videolan.org/ffmpeg.git`. I also tried with libav
I did not put any specific flags  when compiling ffmpeg.
Version 20181221 works for those subs

**Comment by tp0** [comment] 2019-04-22 11:05
This was just fixed. See https://github.com/aajanki/yle-dl/issues/184#issuecomment-485254661

**Comment by kuuntelija** [comment] 2019-05-09 17:06
Just installed version yle-dl-20190502 with ffmpeg version 4.1.3 into slackware 14.2 using slackbuilds script https://slackbuilds.org/slackbuilds/14.2/network/yle-dl.tar.gz.  It has same problem as with previous version ie. no subtitles. When i use earlier version yle-dl-20181221 it loads subtitles just fine.

**Comment by aajanki** [comment] 2019-05-09 18:49
@kuuntelija, can you double check that you are actually running yle-dl-20190502? (I'm asking because the slackbuilds script that you linked contains references to the version 20190331.)

If you do have the latest version, please send me the full output with the -V flag, for example: `yle-dl -V https://areena.yle.fi/1-4438401`. You can send the output by email because it will be quite large: antti.ajanki@iki.fi

**Comment by kuuntelija** [comment] 2019-05-09 19:26
> @kuuntelija, can you double check that you are actually running yle-dl-20190502? (I'm asking because the slackbuilds script that you linked contains references to the version 20190331.)

Yes it is. I used that slcakbuild script but the latest stable source from your page. It compiled just fine and command yle-dl shows yle-dl 20190502 after the usage lines.


> If you do have the latest version, please send me the full output with the -V flag, for example: `yle-dl -V https://areena.yle.fi/1-4438401`. You can send the output by email because it will be quite large: [antti.ajanki@iki.fi](mailto:antti.ajanki@iki.fi)

Do you want also the lines when it is downloading or is before those enough?

**Comment by kuuntelija** [comment] 2019-05-09 19:45
Tässäpä tämä koko debug.log. Video tuli hyvin mutta tekstitys ei ollenkaan.
 

Sent: Thursday, May 09, 2019 at 9:49 PM

**Comment by aajanki** [comment] 2019-06-03 18:00
Closing this issue because it seems that this is fixed by upgrading ffmpeg. If there are more subtitle issues, try to update yle-dl to the latest git version because there are more subtitle fixes.

**Closed by aajanki** 2019-06-03 18:00 UTC
