### ISSUE TITLE
Output filename with spaces results in a mangled URL

### ISSUE THREAD

**Issue by rhoeden** [aajanki/yle-dl#87] opened 2016-12-19 11:26 UTC
I encountered the issue with yle-dl version 2.12 but this happens also with 2.13. Obvious workaround is to use filenames without spaces and rename the file after it has been download.

[yle-dl.txt](https://github.com/aajanki/yle-dl/files/660876/yle-dl.txt)

**Comment by aajanki** [comment] 2016-12-23 08:41
All of your examples work correctly here (Debian unstable, bash 4.4-2), that is they download the stream and the ouput filename contains spaces as expected.

Which OS/distro and which shell are you using? What does `locale` output?

**Comment by rhoeden** [comment] 2016-12-23 14:09
I'm on Arch Linux (up to date) with zsh (5.3.1). Yle-dl is from [aur](https://aur.archlinux.org/packages/yle-dl/l).
The issue persists in other shells as well (bash 4.4.005-2, dash 0.5.9.1 and fish 2.4.0).

```
$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8
```
It makes no difference if I change locale back to the default en_US.UTF-8.

**Comment by hugovk** [comment] 2016-12-23 20:29
The examples also work for me with yle-dl in bash on macOS Sierra.

```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```
```
$ locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

**Comment by aajanki** [comment] 2017-01-05 10:07
Does this happen if you create a new user and login as that user?

Have you observed similar issues with other commands? For example, does `wget http://areena.yle.fi/tv -O "areena etusivu.html"` create an output file with a space?

I'm not able to replicate this on a fresh installation of Arch Linux.

**Comment by rhoeden** [comment] 2017-01-09 08:34
Wgetting with outputting to a filename with spaces works fine. Trying with a new user didn't help. I've also tried removing all locale settings, but problem is still here. I suppose a reinstall is in order, since it seems to make this go away.

**Comment by aajanki** [comment] 2017-01-12 19:02
I'll close this bug because I'm unable to reproduce it.

**Closed by aajanki** 2017-01-12 19:02 UTC
