### ISSUE TITLE
yl-dl (w32) stopped working march 2017

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#94] opened 2017-03-03 10:06 UTC
Sends incorrect manifest string to ADOBEHDS? Gets it wrong from yle?
Hopefully not on purpose? Blacklisted?

First I thght it was missing this --author on now all videos, but not the case.
Used an old test-version which after getting file-name opens firefox, to give me chance to start fragment download wth HDS plugin. (after dldng fragments that way yle-dl assembles fragments to its own file-name, good for encrypted streams).
Also tried then feeding yl-dl the ADOBEHDS manifest back, etc via w32 clipboard but cant get it working, unclear what clipboard does to string,binary,etc formats

It seems the yle-dl manifest have, gets an incorrect (always?) ABCDEF,etc (identification) part while ADOBEHDS gets a more (excpected) random string-thing which works? Otherwise the two manifests are basically the same.
Maybe YLE-server has included some "python-difficult ASCII" or even binary in some earlier straight string response?
Or blacklisted me and/or yle-d?
(yep, dblchckd, after hmac the &g=ABCDEFGHIJKL&hdcore.. string in yle-dl manifest)

I obviously also messed upped my own test code, getting pickling sockets error today, hehe.

PS this "let ADOBEHDS get manifest, dnld the fragments" might also be a good "pre-command" , if yle-dl wld just wait for, use downloaded fragments, not try to do it itself.(after getting fragment filenames and how many. )

**Comment by aajanki** [comment] 2017-03-04 12:50
Try the latest yle-dl code from the Github. There was a minor change in Areena that broke some clips on yle-dl, but that should be fixed by the latest commit.

If that doesn't help, give me an example Areena URL that is causing problems and the error message you get. Or even better, send me the full `yle-dl --verbose` output.

yle-dl has always used `g=ABCDEFGHIJKL` as one of the parameters. It hasn't changed lately so I don't think that it is the root cause.

**Comment by gunnar12** [comment] 2017-03-04 19:56
Thanks for prompt reply!

Made me look elsewhere than yle-dl and there it was, my mess wth adobehds versions and paths..
Guess you have rights to delete this whole message-string-thing?

Gunnar

**Closed** 2017-03-05 14:09 UTC
