### ISSUE TITLE
Downloading fails (no video nor audio, just subtitles partially)

### ISSUE THREAD

**Issue by jluttine** [aajanki/yle-dl#255] opened 2020-11-03 20:12 UTC
Only subtitles downloaded (and partially/corrupted), no video nor audio:

```
$ yle-dl https://areena.yle.fi/1-50173661
yle-dl 20201022: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2020 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Output file: John Wick-2020-11-01T21:00.mkv
[webvtt @ 0x1534180] Dropping 1 duplicated subtitle events
size=      10kB time=00:09:21.69 bitrate=   0.1kbits/s speed=4.77e+03x
Stream saved to John Wick-2020-11-01T21:00.mkv
```

Any ideas what's wrong?

**Comment by aajanki** [comment] 2020-11-05 18:24
Which version of ffmpeg do you have? `ffmpeg -version`

If you analyze the downloaded file with ffprobe, does it detect video or audio streams? `ffprobe "John Wick-2020-11-01T21:00.mkv"`

I'm able to download it with video, audio and subtitles. I have ffmpeg 4.3.1-5.

You can also try the wget backend as a backup download method. It select an alternative stream, which might work even if the default one fails.

`yle-dl --backend wget https://areena.yle.fi/1-50173661`

**Comment by jluttine** [comment] 2020-11-07 18:56
```
$ ffmpeg -version
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9.3.0 (GCC)
configuration: --disable-static --prefix=/nix/store/6vrljdyzrsxnycykijv5v95hjxxqxp7x-ffmpeg-4.3.1 --arch=x86_64 --target_os=linux --enable-gpl --enable-version3 --enable-shared --enable-pic --enable-runtime-cpudetect --enable-hardcoded-tables --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --enable-ffmpeg --disable-ffplay --enable-ffprobe --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-avutil --enable-postproc --enable-swresample --enable-swscale --disable-doc --enable-libass --enable-bzlib --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libmp3lame --enable-iconv --enable-libtheora --enable-libssh --enable-vaapi --enable-libdrm --enable-vdpau --enable-libvorbis --enable-libvpx --enable-lzma --disable-opengl --disable-libmfx --disable-libaom --enable-libpulse --enable-sdl2 --enable-libsoxr --enable-libx264 --enable-libxvid --enable-zlib --enable-libopus --enable-libspeex --enable-libx265 --enable-libdav1d --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

```
$ ffprobe John\ Wick-2020-11-01T21\:00.mkv
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9.3.0 (GCC)
  configuration: --disable-static --prefix=/nix/store/6vrljdyzrsxnycykijv5v95hjxxqxp7x-ffmpeg-4.3.1 --arch=x86_64 --target_os=linux --enable-gpl --enable-version3 --enable-shared --enable-pic --enable-runtime-cpudetect --enable-hardcoded-tables --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --enable-ffmpeg --disable-ffplay --enable-ffprobe --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-avutil --enable-postproc --enable-swresample --enable-swscale --disable-doc --enable-libass --enable-bzlib --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libmp3lame --enable-iconv --enable-libtheora --enable-libssh --enable-vaapi --enable-libdrm --enable-vdpau --enable-libvorbis --enable-libvpx --enable-lzma --disable-opengl --disable-libmfx --disable-libaom --enable-libpulse --enable-sdl2 --enable-libsoxr --enable-libx264 --enable-libxvid --enable-zlib --enable-libopus --enable-libspeex --enable-libx265 --enable-libdav1d --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from 'John Wick-2020-11-01T21:00.mkv':
  Metadata:
    creation_time   : 2020-11-01T19:00:00.000000Z
    ENCODER         : Lavf57.83.100
  Duration: 00:09:24.70, bitrate: 0 kb/s
    Stream #0:0(fi): Subtitle: subrip (default)
    Metadata:
      VARIANT_BITRATE : 3297781
      COMMENT         : käännöstekstitys
      ENCODER         : Lavc57.107.100 srt
      DURATION        : 00:09:24.699000000
    Stream #0:1(fi): Subtitle: subrip (default)
    Metadata:
      VARIANT_BITRATE : 3297781
      COMMENT         : käännöstekstitys
      ENCODER         : Lavc57.107.100 srt
      DURATION        : 00:09:24.699000000
    Stream #0:2(fi): Subtitle: subrip (default)
    Metadata:
      VARIANT_BITRATE : 3297781
      COMMENT         : käännöstekstitys
      ENCODER         : Lavc57.107.100 srt
      DURATION        : 00:09:24.699000000
```

`wget` backend seems to work.

**Comment by aajanki** [comment] 2020-11-08 19:36
Hmm, your ffmpeg seems fine as far as I can see. The only explanation I can think of right now is that you would be missing some video encoding library, but ffmpeg should report an error in that case.

Does it reveal anything more if you try the verbose mode: `yle-dl --verbose https://areena.yle.fi/1-50173661` ? You can even try the `--debug` switch.

**Comment by aajanki** [comment] 2024-06-05 17:08
I'm closing this old bug report because I'm not able to reproduce it and I think that the Areena stream format has changed anyway.

Please feel free to open a new report if you still encounter broken streams!

**Closed by aajanki** 2024-06-05 17:08 UTC
