### ISSUE TITLE
 --backend="ffmpeg" problem for nonSports files?

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#166] opened 2018-09-27 18:29 UTC
Thought it was my partial merg wth V236, but just did a virgin 236 installation on a virgin ubuntu16.04.

Tried both --backend=ffmpeg  and "ffmpeg".

It seems yle-dl picks the wrong HLS link for non-sports when "only ffmpeg" asked for??
Sports stuff goes ok,

With no --backend="ffmpeg" yle-dl obv picks wget and works ok.
(and when a SPorts comes along,., it does ffmpeg correctly)

Unluckily unbu16 has wget1.17, not 1.18, and cant do them multi-GB files without disconnecting.
(used some 10 minutes to try to compile v1.18 but stuck in configure and some missing gnutils..)

Or something else__

..
yle-dl --vfat --backend="ffmpeg" -i aa.txt

yle-dl 2.36: Download media files from Yle Areena and Elävä Arkisto
Output file: Ylen aamu-tv_ Tänään otsikoissa-2018-09-27T15_10.mp4

https://cdnapisec.kaltura.com/p/1955031/sp/195503100/playManifest/entryId/1_05qsfkjl/flavorId/0_xjzlecnk/format/url/protocol/https/a.mp4?referrer=aHR0cHM6Ly9hcmVlbmEueWxlLmZp&playSessionId=11111111-1111-1111-1111-111111111111&clientTag=html5:v2.67&preferredBitrate=600&uiConfId=37558971: Invalid data found when processing input
..
PS  Worse, hehe!  
ffmpeg overwrites any existing file-name due to the -y in the command from yle-dl.
-n might ne better, althgh shld be same as for other backends?
Worse, if that happens, ffmpeg stops and asks, list doesnt continue?

**Comment by gunnar12** [comment] 2018-09-27 18:57
btw, going "virgin install" I also run intoo problems with


sudo apt-get install rtmpdump wget ffmpeg python3-dev python3-setuptools \
    python3-pip python3-pycryptodome python3-requests python3-lxml python3-socks \
    php-cli php-curl php-xml php-bcmath

ubu16 cldnt find  python3-pycryptodome package.

However, continuing to next step, running the yle-dl pyhon setup.py (re-)installed lotsa stuff, among them pycryptodome correctly..

**Comment by aajanki** [comment] 2018-09-30 17:03
Works for me with ffmpeg 4.0.2. The error is coming from ffmpeg, so it could be that your version of ffmpeg does not support that stream. Which version of ffmpeg are you using?

Can you provide the verbose output of `yle-dl --vfat --backend=ffmpeg --verbose https://areena.yle.fi/1-4292785`?

**Comment by gunnar12** [comment] 2018-09-30 18:52
Works for me with ffmpeg 4.0.2. T/

same ffmpeg works with v2.33,

Same true on the ancient vista running an ancient mingw-ffmpeg (bc new ones dont work wth vista)

Seems yle-dl builds the stream link wrong for "still normal" nonSports when --backend="ffmpeg" (or =ffmpeg, etc) used as argument (which I guess few use)

Note, the " Invalid data found when processing input" is from ffmpeg, unluckily it has already over-written the header to the file.

**Comment by aajanki** [comment] 2018-10-02 17:09
Can you provide the exact yle-dl command line options that cause the error and also the `--verbose` log from the run?

**Comment by gunnar12** [comment] 2018-10-02 18:48
the exact yle-dl command line/

he,he, not now... I am in the middle of running yle-dl on three machines, combined ubuntu-windos network and at least 12 different ways of starting yle-dl in different places.. while getting the output files to two different places..

PS after some days I will build a "test-and-make-and-debug" directory, but first I need to get the virgin and stone-aged machines working together... while yle-dl downloads what disappears in some days.

**Comment by aajanki** [comment] 2018-10-22 18:38
I'm closing this bug report because I can't reproduce it. Reopen, if you manage to find a command line that shows the problem.

**Closed by aajanki** 2018-10-22 18:38 UTC
