### ISSUE TITLE
Yle Areena Audio podcastit: "requests.exceptions.HTTPError: 404 Client Error: Not Found"

### ISSUE THREAD

**Issue by doctorcolossus** [aajanki/yle-dl#306] opened 2022-04-24 05:31 UTC
I am getting 404 not-found errors from the URLs yle-dl seems to generate in order to try to process any podcast playlist.

I've tried both with yle-dl pip-installed from pypy, as well as from the master branch cloned from this repository.

This example is for [Uutispodcast](https://areena.yle.fi/audio/1-61894955):

```
$ yle-dl -V https://areena.yle.fi/audio/1-50674174
yle-dl 20220213: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2022 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

DEBUG: https://areena.yle.fi/audio/1-50674174 is an audio URL
DEBUG: HTTP GET https://areena.yle.fi/audio/1-50674174
DEBUG: HTTP status code: 200
DEBUG: HTTP response headers:
DEBUG: Content-Type: text/html; charset=utf-8
DEBUG: Transfer-Encoding: chunked
DEBUG: Connection: keep-alive
DEBUG: Server: CloudFront
DEBUG: Date: Sun, 24 Apr 2022 05:28:46 GMT
DEBUG: X-Powered-By: Express
DEBUG: X-Frame-Options: DENY
DEBUG: ETag: W/"36f1d-G4ubpJK/FlJVCYMdPXo//jSVx3w"
DEBUG: Content-Encoding: gzip
DEBUG: Vary: Accept-Encoding
DEBUG: X-Cache: Hit from cloudfront
DEBUG: Via: 1.1 e9ba0a9a729ff2960a04323bf1833df8.cloudfront.net (CloudFront)
DEBUG: X-Amz-Cf-Pop: SFO5-C3
DEBUG: X-Amz-Cf-Id: opmrhx5lIYnRN7AOI923ySiCw3KSLWcTtqDjeM8XwlzP108C8GP9Cw==
DEBUG: Age: 14
DEBUG: HTML meta charset: UTF-8
DEBUG: Getting a playlist page 1-50674174, size = 100, offset = 0
DEBUG: HTTP GET https://areena.yle.fi/api/programs/v1/episodes/1-50674174.json?type=program&availability=&limit=100&order=episode.hash%3Aasc%2Cpublication.starttime%3Aasc%2Ctitle.fi%3Aasc&app_id=areena_web_radio_prod&app_key=b3a0dc973c0aab997f1021bc7a0e3157
DEBUG: HTTP status code: 404
DEBUG: HTTP response headers:
DEBUG: Content-Type: text/html; charset=utf-8
DEBUG: Transfer-Encoding: chunked
DEBUG: Connection: keep-alive
DEBUG: Date: Sun, 24 Apr 2022 05:29:02 GMT
DEBUG: Set-Cookie: yle_selva=16507781420953786771; Domain=.yle.fi; Path=/; Expires=Thu, 31 Dec 2037 23:59:59 GMT
DEBUG: Cache-Control: private, max-age=120
DEBUG: X-Frame-Options: DENY
DEBUG: X-Content-Type-Options: nosniff
DEBUG: ETag: W/"1877b-cPGMraEoSdwUFGd2r6rUpXcP/0Q"
DEBUG: Content-Encoding: gzip
DEBUG: Vary: Accept-Encoding
DEBUG: X-Cache: Error from cloudfront
DEBUG: Via: 1.1 e9ba0a9a729ff2960a04323bf1833df8.cloudfront.net (CloudFront)
DEBUG: X-Amz-Cf-Pop: SFO5-C3
DEBUG: X-Amz-Cf-Id: H5XkH1Cl1kuSLsW4y1mNP3RdXDYRnBKS4a4uqPx7ZcNyupizR7iRzQ==
Traceback (most recent call last):
  File "/usr/bin/yle-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/yledl/yledl.py", line 497, in main
    res = execute_action(
  File "/usr/lib/python3.10/site-packages/yledl/yledl.py", line 267, in execute_action
    res = _internal_execute_action(
  File "/usr/lib/python3.10/site-packages/yledl/yledl.py", line 312, in _internal_execute_action
    return download_clips(clips(), dl, io, title_formatter, stream_filters)
  File "/usr/lib/python3.10/site-packages/yledl/yledl.py", line 294, in clips
    return extractor.extract(url, stream_filters.latest_only,
  File "/usr/lib/python3.10/site-packages/yledl/extractors.py", line 216, in extract
    playlist = self.guarded_get_playlist(url, latest_only)
  File "/usr/lib/python3.10/site-packages/yledl/extractors.py", line 224, in guarded_get_playlist
    return self.get_playlist(url, latest_only)
  File "/usr/lib/python3.10/site-packages/yledl/extractors.py", line 738, in get_playlist
    return self.playlist_episode_urls(series_id, latest_only)
  File "/usr/lib/python3.10/site-packages/yledl/extractors.py", line 302, in playlist_episode_urls
    page = self.playlist_page(series_id, sort_order, page_size, offset)
  File "/usr/lib/python3.10/site-packages/yledl/extractors.py", line 317, in playlist_page
    playlist = self.httpclient.download_json(pl_url)
  File "/usr/lib/python3.10/site-packages/yledl/http.py", line 52, in download_json
    response = self.get(url, extra_headers)
  File "/usr/lib/python3.10/site-packages/yledl/http.py", line 101, in get
    r.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://areena.yle.fi/api/programs/v1/episodes/1-50674174.json?type=program&availability=&limit=100&order=episode.hash%3Aasc%2Cpublication.starttime%3Aasc%2Ctitle.fi%3Aasc&app_id=areena_web_radio_prod&app_key=b3a0dc973c0aab997f1021bc7a0e3157
```

Indeed, navigating to https://areena.yle.fi/api/programs/v1/episodes/1-50674174.json in my browser, there is no such page: "Voi jehna! Sivua ei löydy. Jos etsit jotakin tiettyä ohjelmaa, kokeile hakua." I am able to listen to the podcasts normally in my browser if I visit the original URL, in the form I passed it in the command argument.

Am I doing something wrong, or is this a bug or regression?

**Comment by aajanki** [comment] 2022-04-24 09:57
There has been some changes on the Areena side and because of those the latest published version of yle-dl isn't working anymore.

There is a partial fix on the master branch. I'll release a new version after I get a few more issues fixed.

Duplicate of #304

**Comment by doctorcolossus** [comment] 2022-04-24 12:17
Okay, thanks!

**Closed** 2022-04-24 20:22 UTC

**Comment by gunnar12** [comment] 2022-04-24 20:30
easy-install.pth

My old always problem
On windos now no easy linux but
1. in at least two places, users and admm "local",  ???
Pythom profuces a bunch of :"egg" packet and more whuch toghether foes the progtsm
library, intern funtiond ets
2. task,
3. 
4.  Pythom profuces a bunch of :"egg" packet and more whuch toghether foes the progtsm
eggs" library, intern funtiond ets

easy-install.pthhas a list of all python programs with sublist of the diretories, names

Stoopid python starts seaching list, picks first match
Stoopid because uninstall, etc is even stoopider

resuly "half of what python tries to run is old, new or just wrong"

TAKE A COPY and delete yle-dl, 
after check there isnt many


 check ir doesnt run at all  YOU GOT THE RIGHT ONE

uninstall see if it disappears in list??
try delete, hehe...

re-install

repeat for hours and days
tr-install linux from zero

**Comment by doctorcolossus** [comment] 2022-04-25 04:58
@gunnar12 I think you need to open a separate issue for that, but it sounds like maybe it's a problem with Python and not yle-dl.
