### ISSUE TITLE
yle-dl shoots error "ModuleNotFoundError: No module named 'pkg_resources'" when being run, even after installing

### ISSUE THREAD

**Issue by esaruoho** [aajanki/yle-dl#172] opened 2018-11-06 21:15 UTC
```
$ yle-dl
Traceback (most recent call last):
  File "/usr/local/Cellar/yle-dl/2.34_1/libexec/bin/yle-dl", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

i tried uninstalling and reinstalling from homebrew, didn't seem to help. what should i do?

**Comment by aajanki** [comment] 2018-11-08 16:38
pkg_resources should be provided by the setuptools package. See if upgrading setuptools helps:
```
pip install --upgrade setuptools
```

**Comment by aajanki** [comment] 2018-12-21 13:19
I'm closing this issue assuming that it was caused by a missing/outdated setuptools. Please, reopen if think that is not the cause.

**Closed by aajanki** 2018-12-21 13:19 UTC

**Comment by esaruoho** [comment] 2019-01-02 13:37
yeah, after screwing around with python, pip and `Frameworks` folder access, I got pip running and yle-dl no longer shoots this error. I wish there was some way of telling a person that they've gone and screwed up everything, instead of forcing them to come over here and ask what's going on and then find out on their own as to how to fix it.
