### ISSUE TITLE
Installation from sources fail: 'yle-dl==2.30' distribution was not found

### ISSUE THREAD

**Issue by jk-1** [aajanki/yle-dl#142] opened 2017-12-31 10:52 UTC
I installed yle-dl from sources according to these instructions:  https://github.com/aajanki/yle-dl/blob/master/OS-install-instructions.md

	sudo apt-get install git rtmpdump wget ffmpeg python-dev python-setuptools python-crypto python-requests python-lxml php-cli php-curl php-mcrypt php-xml php-bcmath

	sudo phpenmod mcrypt

	git clone https://github.com/aajanki/yle-dl.git

	cd yle-dl

	sudo -H python setup.py install

Then I fixed yle-dl permissions: 

	sudo chmod 0755 /usr/local/bin/yle-dl

And tried to run it, but got following error:

	yle-dl --help
	Traceback (most recent call last):
	  File "/usr/local/bin/yle-dl", line 5, in <module>
		from pkg_resources import load_entry_point
	  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
		@_call_aside
	  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
		f(*args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
		working_set = WorkingSet._build_master()
	  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
		ws.require(__requires__)
	  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
		needed = self.resolve(parse_requirements(requirements))
	  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
		raise DistributionNotFound(req, requirers)
	pkg_resources.DistributionNotFound: The 'yle-dl==2.30' distribution was not found and is required by the application

How to fix this? Thank you for your support.

There was no earlier yle-dl installation in this environment before I tried to install it from sources. Previous error report was run on different environment.

OS is Ubuntu 16.04.

Install trace is as follows:

	git clone https://github.com/aajanki/yle-dl.git
	Cloning into 'yle-dl'...
	remote: Counting objects: 2792, done.
	remote: Total 2792 (delta 0), reused 0 (delta 0), pack-reused 2792
	Receiving objects: 100% (2792/2792), 1.13 MiB | 516.00 KiB/s, done.
	Resolving deltas: 100% (1873/1873), done.
	Checking connectivity... done.

	cd yle-dl/

	~/yle-dl$ sudo -H python setup.py install
	running install
	running bdist_egg
	running egg_info
	creating yle_dl.egg-info
	writing requirements to yle_dl.egg-info/requires.txt
	writing yle_dl.egg-info/PKG-INFO
	writing top-level names to yle_dl.egg-info/top_level.txt
	writing dependency_links to yle_dl.egg-info/dependency_links.txt
	writing entry points to yle_dl.egg-info/entry_points.txt
	writing manifest file 'yle_dl.egg-info/SOURCES.txt'
	reading manifest file 'yle_dl.egg-info/SOURCES.txt'
	reading manifest template 'MANIFEST.in'
	writing manifest file 'yle_dl.egg-info/SOURCES.txt'
	installing library code to build/bdist.linux-x86_64/egg
	running install_lib
	running build_py
	creating build
	creating build/lib.linux-x86_64-2.7
	creating build/lib.linux-x86_64-2.7/yledl
	copying yledl/__init__.py -> build/lib.linux-x86_64-2.7/yledl
	copying yledl/yledl.py -> build/lib.linux-x86_64-2.7/yledl
	copying yledl/utils.py -> build/lib.linux-x86_64-2.7/yledl
	copying yledl/version.py -> build/lib.linux-x86_64-2.7/yledl
	copying yledl/downloaders.py -> build/lib.linux-x86_64-2.7/yledl
	copying yledl/hds.py -> build/lib.linux-x86_64-2.7/yledl
	copying yledl/AdobeHDS.php -> build/lib.linux-x86_64-2.7/yledl
	creating build/bdist.linux-x86_64
	creating build/bdist.linux-x86_64/egg
	creating build/bdist.linux-x86_64/egg/yledl
	copying build/lib.linux-x86_64-2.7/yledl/__init__.py -> build/bdist.linux-x86_64/egg/yledl
	copying build/lib.linux-x86_64-2.7/yledl/yledl.py -> build/bdist.linux-x86_64/egg/yledl
	copying build/lib.linux-x86_64-2.7/yledl/utils.py -> build/bdist.linux-x86_64/egg/yledl
	copying build/lib.linux-x86_64-2.7/yledl/version.py -> build/bdist.linux-x86_64/egg/yledl
	copying build/lib.linux-x86_64-2.7/yledl/downloaders.py -> build/bdist.linux-x86_64/egg/yledl
	copying build/lib.linux-x86_64-2.7/yledl/hds.py -> build/bdist.linux-x86_64/egg/yledl
	copying build/lib.linux-x86_64-2.7/yledl/AdobeHDS.php -> build/bdist.linux-x86_64/egg/yledl
	byte-compiling build/bdist.linux-x86_64/egg/yledl/__init__.py to __init__.pyc
	byte-compiling build/bdist.linux-x86_64/egg/yledl/yledl.py to yledl.pyc
	byte-compiling build/bdist.linux-x86_64/egg/yledl/utils.py to utils.pyc
	byte-compiling build/bdist.linux-x86_64/egg/yledl/version.py to version.pyc
	byte-compiling build/bdist.linux-x86_64/egg/yledl/downloaders.py to downloaders.pyc
	byte-compiling build/bdist.linux-x86_64/egg/yledl/hds.py to hds.pyc
	creating build/bdist.linux-x86_64/egg/EGG-INFO
	copying yle_dl.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying yle_dl.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying yle_dl.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying yle_dl.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying yle_dl.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying yle_dl.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	zip_safe flag not set; analyzing archive contents...
	creating dist
	creating 'dist/yle_dl-2.30-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
	removing 'build/bdist.linux-x86_64/egg' (and everything under it)
	Processing yle_dl-2.30-py2.7.egg
	Copying yle_dl-2.30-py2.7.egg to /usr/local/lib/python2.7/dist-packages
	Adding yle-dl 2.30 to easy-install.pth file
	Installing yle-dl script to /usr/local/bin

	Installed /usr/local/lib/python2.7/dist-packages/yle_dl-2.30-py2.7.egg
	Processing dependencies for yle-dl==2.30
	Searching for PyAMF
	Reading https://pypi.python.org/simple/PyAMF/
	Best match: PyAMF 0.8.0
	Downloading https://pypi.python.org/packages/a0/06/43976c0e3951b9bf7ba0d7d614a8e3e024eb5a1c6acecc9073b81c94fb52/PyAMF-0.8.0.tar.gz#md5=51e810531a663b55e686286edb23e82a
	Processing PyAMF-0.8.0.tar.gz
	Writing /tmp/easy_install-GQqJ6w/PyAMF-0.8.0/setup.cfg
	Running PyAMF-0.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-GQqJ6w/PyAMF-0.8.0/egg-dist-tmp-YwoBdL
	no previously-included directories found matching 'doc/build'
	no previously-included directories found matching 'doc/_build'
	warning: no previously-included files matching '*.swf' found anywhere in distribution
	warning: no previously-included files matching '*.pyc' found anywhere in distribution
	creating /usr/local/lib/python2.7/dist-packages/PyAMF-0.8.0-py2.7-linux-x86_64.egg
	Extracting PyAMF-0.8.0-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
	Adding PyAMF 0.8.0 to easy-install.pth file

	Installed /usr/local/lib/python2.7/dist-packages/PyAMF-0.8.0-py2.7-linux-x86_64.egg
	Searching for future
	Reading https://pypi.python.org/simple/future/
	Best match: future 0.16.0
	Downloading https://pypi.python.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz#md5=3e8e88a2bda48d54b1da7634d04760d7
	Processing future-0.16.0.tar.gz
	Writing /tmp/easy_install-EboNKU/future-0.16.0/setup.cfg
	Running future-0.16.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-EboNKU/future-0.16.0/egg-dist-tmp-yV4sQY
	warning: no files found matching '*.au' under directory 'tests'
	warning: no files found matching '*.gif' under directory 'tests'
	warning: no files found matching '*.txt' under directory 'tests'
	zip_safe flag not set; analyzing archive contents...
	future.standard_library.__init__: module references __file__
	future.standard_library.__init__: module references __path__
	future.utils.__init__: module MAY be using inspect.stack
	future.backports.test.ssl_servers: module references __file__
	future.backports.test.support: module references __file__
	past.translation.__init__: module references __file__
	past.translation.__init__: module references __path__
	past.builtins.misc: module MAY be using inspect.stack
	creating /usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg
	Extracting future-0.16.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
	Adding future 0.16.0 to easy-install.pth file
	Installing pasteurize script to /usr/local/bin
	Installing futurize script to /usr/local/bin

	Installed /usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg
	Searching for defusedxml
	Reading https://pypi.python.org/simple/defusedxml/
	Best match: defusedxml 0.5.0
	Downloading https://pypi.python.org/packages/74/ba/4ba4e89e21b5a2e267d80736ea674609a0a33cc4435a6d748ef04f1f9374/defusedxml-0.5.0.tar.gz#md5=7ff1501366c6d1dcd2de8514dc2b755e
	Processing defusedxml-0.5.0.tar.gz
	Writing /tmp/easy_install-MSDONX/defusedxml-0.5.0/setup.cfg
	Running defusedxml-0.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MSDONX/defusedxml-0.5.0/egg-dist-tmp-5gp6jE
	zip_safe flag not set; analyzing archive contents...
	Moving defusedxml-0.5.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
	Adding defusedxml 0.5.0 to easy-install.pth file

	Installed /usr/local/lib/python2.7/dist-packages/defusedxml-0.5.0-py2.7.egg
	Searching for lxml==3.5.0
	Best match: lxml 3.5.0
	Adding lxml 3.5.0 to easy-install.pth file

	Using /usr/lib/python2.7/dist-packages
	Searching for requests==2.9.1
	Best match: requests 2.9.1
	requests 2.9.1 is already the active version in easy-install.pth

	Using /usr/lib/python2.7/dist-packages
	Searching for pycrypto==2.6.1
	Best match: pycrypto 2.6.1
	pycrypto 2.6.1 is already the active version in easy-install.pth

	Using /usr/lib/python2.7/dist-packages
	Finished processing dependencies for yle-dl==2.30

**Comment by aajanki** [comment] 2018-01-02 11:01
It looks like yle-dl is installed correctly, but when you try to execute it Python doesn't find the installed modules. 

Do you have several Python version/environments installed (using pyenv or similar)?

Do you have the `$PYTHONPATH` environment variable set? Run `export | grep PYTHONPATH`. If it outputs something, you have the environment variable defined. You might want to try reinstalling with it.

What is the Python module import path? Execute this: `/usr/bin/python -c 'import sys; print(sys.path)'`. The output should contain at least `/usr/local/lib/python2.7/dist-packages/yle_dl-2.30-py2.7.egg`.

**Comment by jk-1** [comment] 2018-01-03 06:04
How can I find out if there are several Python version/environments installed?


	jk@mypc:~$ export | grep PYTHONPATH

	jk@mypc:~$ /usr/bin/python -c 'import sys; print(sys.path)'
	['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', 
	'/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0']

	jk@mypc:~$ which yle-dl
	/usr/local/bin/yle-dl

**Comment by aajanki** [comment] 2018-01-05 13:19
So for some reason your Python module import path incudes `/usr/lib/python2.7/dist-packages` but not the *.egg files in that directory as is should, which is why Python can't find the yle-dl module.

[This](https://stackoverflow.com/a/18796013) stackoverflow answer says that one possible reason for this situation is that the files don't have read permissions. You also mentioned that you had to fix the permissions for `/usr/local/bin/yle-dl`. For me the permissions are automatically correct. It could be that on your system setup.py is giving read permissions for root only. I'm not sure why that would happen.

Make sure that all files and directories under `/usr/lib/python2.7/dist-packages` have read permission for everybody:

```
sudo chmod -R go+rX /usr/local/lib/python2.7/dist-packages
```

If that doens't help, the same Stackoverflow thread includes also other possible fixes.

**Comment by gunnar12** [comment] 2018-01-06 09:50
/usr/lib/python2.7/dist-packages /

Had similar problems when somehow  an old version-path "forgotten" in, if I remember right,,  /usr/lib/python2.7/easy-install.pth
Or some similar file for python that containes a list to the egg-files.
Pyhon just picked first (old and wrong) yle-dl path in list and crashed,
the correct one was below the wrong one in the list

Obv helped deleting the wrong old one

**Comment by aajanki** [comment] 2018-04-15 08:29
Still not sure what is causing this, but I have changed the documentation to recommend installing to the user home directory. It should help at least if the issue was wrong permissions.

First, remove old globally installed version:
```
sudo pip uninstall yle-dl
```

Then install to the home directory without sudo:
```
pip3 install --user --upgrade yle-dl
```

**Comment by aajanki** [comment] 2018-06-19 16:15
I'm closing this issue because I can reproduce it. I still think this is related to wrong permissions on the Python files.

**Closed by aajanki** 2018-06-19 16:15 UTC
